repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
- repo: https://gitlab.com/iamlikeme/nbhooks
  rev: 1.0.0  # Set to the most recent version
  hooks:
  - id: nb-ensure-clean
    args: [--meta, ExecuteTime]  # Optional blacklist of metadata keys (you can use regex)
